FROM rickgong/centos-base:1.0

yum -y install openldap compat-openldap openldap-clients openldap-servers openldap-servers-sql openldap-devel

MAINTAINER  rick gong "rickgong@outlook.com"
LABEL name="openldap"

CMD ["/bin/bash"]