FROM rickgong/centos-base:1.0

RUN yum -y install openldap compat-openldap openldap-clients openldap-servers openldap-servers-sql openldap-devel
RUN slappasswd -s synnex>adminpwd

MAINTAINER  rick gong "rickgong@outlook.com"
LABEL name="openldap"

CMD ["/bin/bash"]